name: aura_i18n
description: "This package handles the internationalization for Aura applications."
version: 1.1.0
homepage: https://github.com/Aura-Corporate/aura-i18n
repository: https://github.com/Aura-Corporate/aura-i18n

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  slang_flutter: ^4.14.0
  slang: ^4.14.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
